[workspace]
resolver = "2"
members = [
  "crates/jalm_syntax",
  "crates/jalm_parser",
  "crates/jalm_ast",
  "crates/jalm_formatter",
  "crates/jalm_typecheck",
  "crates/jalm_effectcheck",
  "crates/jalm_codegen",
  "crates/jalm_runtime",
  "crates/jalm_tests",
  "crates/jalmt",
]
